"""add snacks catalog table (§13.3b)

Revision ID: 161ee7d4a387
Revises: 411ae4b3dccc
Create Date: 2026-08-07 23:49:21.960160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '161ee7d4a387'
down_revision = '411ae4b3dccc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snack',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('snack', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_snack_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('snack', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_snack_name'))

    op.drop_table('snack')
    # ### end Alembic commands ###
