"""add meal/category/date indexes for query performance (audit §9.1)

Revision ID: 2d2d16ec2886
Revises: 8b1c2d3e4f5a
Create Date: 2026-08-05 23:07:04.985339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d2d16ec2886'
down_revision = '8b1c2d3e4f5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal', schema=None) as batch_op:
        batch_op.create_index('ix_meal_category', ['category'], unique=False)
        batch_op.create_index('ix_meal_name', ['name'], unique=False)

    with op.batch_alter_table('used_meal', schema=None) as batch_op:
        batch_op.create_index('ix_used_meal_date', ['date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('used_meal', schema=None) as batch_op:
        batch_op.drop_index('ix_used_meal_date')

    with op.batch_alter_table('meal', schema=None) as batch_op:
        batch_op.drop_index('ix_meal_name')
        batch_op.drop_index('ix_meal_category')

    # ### end Alembic commands ###
