"""add purchased column to weekly_menu

Revision ID: 411ae4b3dccc
Revises: a3b7c9d1e2f4
Create Date: 2026-08-07 22:51:49.300405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '411ae4b3dccc'
down_revision = 'a3b7c9d1e2f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_menu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchased', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_menu', schema=None) as batch_op:
        batch_op.drop_column('purchased')

    # ### end Alembic commands ###
