"""add week_start column to WeeklyMenu (§13a.2)

Revision ID: b89397ee94f2
Revises: e7a5b68655d5
Create Date: 2026-08-12 01:55:28.886364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b89397ee94f2'
down_revision = 'e7a5b68655d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_menu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('week_start', sa.String(length=10), nullable=True))
        batch_op.create_index(batch_op.f('ix_weekly_menu_week_start'), ['week_start'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_menu', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weekly_menu_week_start'))
        batch_op.drop_column('week_start')

    # ### end Alembic commands ###
